{
 "title": "PriceSources",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "PriceSource",
    "query": "SELECT label || '-' || type || '---' || id as vars FROM price_source;"
   }
  ]
 },
 "panels": [
  {
   "title": "${PriceSource} - 24H MA with BB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  at AS \"time\",\n  usd_value, average(tw_value) as twap, average(tw_value) + stddev(agg) as bb_up, average(tw_value) - stddev(agg) as bb_down\nFROM (select  \t\tprice_source_id,  \t\tat,  \t\tusd_value,  \t\tstats_agg(usd_value) OVER timespan as agg, \t\ttime_weight('Linear', at, usd_value) over timespan as tw_value \tfrom price_entries \twindow timespan as (partition by price_source_id order by at range '24 hours' preceding) \t) tw\nWHERE\n  price_source_id = ${PriceSource}\nORDER BY 1"
    }
   ]
  },
  {
   "title": "${PriceSource}",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  bucket AS \"time\",\n  open, high, low, close\nFROM five_min_buckets\nWHERE\n  $__timeFilter(bucket) AND\n  price_source_id = ${PriceSource}\nORDER BY 1"
    }
   ]
  },
  {
   "title": "1h price average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  at AS \"time\",\n  usd_value, average(avg_value) as avg\nFROM (select  \t\tprice_source_id,  \t\tat,  \t\tusd_value,  \t\ttime_weight('Linear', at, usd_value)  \t\t\tOVER(partition by price_source_id order by at range '1 hour' preceding) as avg_value  \tfrom price_entries) tw\nWHERE\n  price_source_id = '$PriceSource'\nORDER BY 1"
    }
   ]
  }
 ]
}